// Versioned Session timeline schema (PRD P0-9). One ordered log per Session; the single source of truth for
// Process. Every event carries `t`, ms since the Session's t0 (see clock.ts). Span events (stroke,
// annotation, transcript_segment) put the span start in `t` and the end in `t_end`.
//
// Field names are snake_case because they are the documented JSON format (docs/schema/session.schema.json,
// generated by `pnpm schema`). Bump SCHEMA_VERSION on any breaking change.
import { z } from 'zod';

// v2 (Slice 2): Candidate relation "descendant" and `classes`; session.json gains optional change_items.
// v3 (Slice 3): Annotation `connector`, close reason `pause`, `via` on pause/resume, `target` on voice_command,
// and the `speech_activity` event (VAD speech spans).
// v4 (Slice 4): review-page edits, appended after the Session: `transcript_edit` and `item_edit`.
// v5 (Slice 5): live Draft Items. `draft_item` carries its pass, model, intent, transcript and a Location summary;
// `draft_action` says `source` (click | voice) instead of `via`.
// v6 (Slice 6): transcription tiers and re-transcription. `transcript_segment` gains `run_id` (null: the live
// run); `transcription_run` records a re-transcription and makes it the active run; `transcript_select` switches
// the active run back or forth.
// v7 (Slice 7): `session_start.clicked_at` (epoch ms of the Start click, for the Start→recording metric);
// session.json's `process_run` gains `windows`, `dropped_annotations` and `unaccounted_annotations`, and a
// `process_runs` summary lists every run, failed ones included (PRD §8 processing failure rate).
// v8 (feedback batch 1, U5): `overlay` on session_start and navigation says whether the page could be drawn on
// ('none': another extension's page or a chrome:// page, where no script of ours runs); screenshot trigger
// `shortcut` (the Alt+Shift+S command, the only way to screenshot those pages).
// v9 (E2, Inspect): close reason `inspect_pick` (an element picked with Inspect is an Annotation with no Strokes and
// one definite Candidate); the `style_edit` event (the reviewer's live style and text edits of a picked element).
// v10 (E3): the `text_comment` event (a comment typed on selected text, with a text-quote anchor), close reason and
// screenshot trigger `text_comment`.
// v11 (E6): `viewport_change`, the toolbar's viewport control resizing the page (the frame host).
// v12 (E4, E5): Candidate `source` (the component file, line and owner chain the page's framework reports), Annotation
// `crop` (a second image of the picked element), blob kind `screenshot_crop`; Change Item Locations carry `source`
// and Evidence `crops`. Annotations from the page API (`window.__inkup.annotate`): `source: 'page_api'`, no
// Strokes, close reason and screenshot trigger `page_api`, the script's `page_api` {comment} (its style and text
// changes are `style_edit` events on the Annotation); Change Item `source`.
// v13 (E7, Object Select): close reason `inspect_pick` is renamed `object_select`; an Annotation carries the comment
// typed on an Object Select pick (`comment`, null otherwise).
// v14 (E12, combined merge): an `item_edit` `edit` op may change `agent_prompt` and `ambiguity` (null clears it) and
// carries `origin: 'combine'` when the merge model wrote it after a merge rather than the reviewer.
// v15 (E10, Mute): `mic_muted` and `mic_unmuted`, the reviewer turning the microphone off and on mid-Session (the audio
// holds silence there, and nothing was transcribed or heard as a Voice Command).
// v16 (E11, dictation and voice-less Sessions): `transcript_segment.target` (speech dictated into a comment box, which
// is the comment's text and not the Session transcript); `session_start.voice` (false: started without a microphone)
// and `voice_on` (the microphone was turned on mid-Session).
// v17 (E9, overlay cleanup): close reason `cleared` (the toolbar's Clear all closed the Annotation; no screenshot), and
// the `overlay_cleared` event.
// v18 (E8, adaptive contrast): a Stroke records its ink `color` (absent before: the old red).
// v19 (F5, review-page Undo/Redo): item_edit ops `undo` and `redo`.
export const SCHEMA_VERSION = 19 as const;

/** ms since t0. */
export const Offset = z.number().int().nonnegative().describe('ms since the Session t0');
export const PointSchema = z.object({ x: z.number(), y: z.number() });
export const RectSchema = z
  .object({ x: z.number(), y: z.number(), width: z.number().nonnegative(), height: z.number().nonnegative() })
  .describe('page coordinates, CSS px');
export const SizeSchema = z.object({ width: z.number().nonnegative(), height: z.number().nonnegative() });

/** Where the page was when something was captured. */
export const PageContextSchema = z.object({
  url: z.string(),
  scroll: PointSchema.describe('page scroll offset (scrollX, scrollY), CSS px'),
  viewport: SizeSchema.describe('viewport size, CSS px'),
  dpr: z.number().positive().describe('devicePixelRatio'),
});

export const TimestampQuality = z.enum(['word', 'approximate']);
export type TimestampQuality = z.infer<typeof TimestampQuality>;

/**
 * Why an Annotation closed (PRD P0-3). `pause`: the Session was paused with the Annotation open. `object_select`: an
 * element was picked with Object Select; the pick is itself an Annotation with this reason, and it closes the open one.
 * `text_comment`: a Text Comment was saved. `cleared`: the reviewer cleared the overlay (Clear all); no screenshot.
 */
export const CloseReason = z.enum([
  'time_gap',
  'scroll',
  'navigation',
  'speech_boundary',
  'draw_toggle',
  'voice_command',
  'pause',
  'session_end',
  'object_select',
  'text_comment',
  'page_api',
  'cleared',
]);
export type CloseReason = z.infer<typeof CloseReason>;

export const ShapeClass = z.enum(['circle', 'underline', 'arrow', 'scribble', 'freeform']);

/**
 * Where an element comes from in the page's source code, as its framework reports it in a development build: the
 * React fiber (`_debugSource`, or the owner stack on React 19), Vue's component `__file`, or `data-source-file`
 * attributes a build plugin adds. Paths start at src/ or app/ when they contain one.
 */
export const SourceSchema = z.object({
  file: z
    .string()
    .optional()
    .describe('source file, from src/ or app/ when the path has one, e.g. src/components/Button.tsx'),
  line: z.number().int().positive().optional().describe('1-based line in that file'),
  components: z
    .array(z.string())
    .max(8)
    .describe('the components that rendered the element, nearest first; minified names left out'),
});
export type Source = z.infer<typeof SourceSchema>;

export const CandidateSchema = z.object({
  selector: z.string().describe('stable CSS selector that resolves to this element on the page'),
  tag: z.string().describe('lower-case tag name'),
  role: z.string().nullable().describe('ARIA role (explicit or implicit)'),
  name: z.string().max(200).describe('accessible name, truncated to 200 chars'),
  text: z.string().max(200).describe('visible text, whitespace-collapsed, truncated to 200 chars'),
  testid: z.string().nullable(),
  id: z.string().nullable(),
  classes: z
    .array(z.string())
    .max(8)
    .default([])
    .describe('class names, generated and utility classes removed (appearance hints: a link styled .btn is a button)'),
  bbox: RectSchema,
  relation: z.enum(['pick', 'ancestor', 'sibling', 'descendant']).describe('relation to the geometric pick'),
  coverage: z.number().min(0).max(1).describe('fraction of the Annotation bbox this element covers'),
  source: SourceSchema.optional().describe(
    'absent when the page reports no source (a production build, or no framework)',
  ),
});
export type Candidate = z.infer<typeof CandidateSchema>;

/** 'page': the drawing overlay runs there. 'none': the page runs no script of ours (URL, speech and screenshots only). */
export const OverlayMode = z.enum(['page', 'none']);
export type OverlayMode = z.infer<typeof OverlayMode>;
const overlayField = OverlayMode.default('page').describe(
  "'none': no drawing possible on this page (another extension's page or chrome://); Locations there are URL + screenshot only",
);

const base = <T extends string>(type: T) => z.object({ id: z.string().min(1), type: z.literal(type), t: Offset });

export const TranscriptionInfoSchema = z.object({
  engine: z.string().describe('adapter id, e.g. webspeech, scripted, whisper, deepgram, elevenlabs'),
  local: z.boolean().nullable().describe('true when audio never leaves the machine; null when unknown'),
  timestamp_quality: TimestampQuality,
});

export const SessionStartEvent = base('session_start').extend({
  tab_id: z.number().int(),
  url: z.string(),
  title: z.string(),
  t0: z.number().int().nonnegative().describe('epoch ms of the Session clock origin'),
  clicked_at: z
    .number()
    .int()
    .nonnegative()
    .nullable()
    .default(null)
    .describe(
      'epoch ms of the Start click, before the screen picker; Start→recording latency = t0 + media.audio.start_offset_ms − clicked_at',
    ),
  overlay: overlayField,
  voice: z
    .boolean()
    .default(true)
    .describe('false: the Session started without a microphone (no audio or transcript until `voice_on`)'),
});
/** A Session started without a microphone got one ("Turn on voice", E11): audio and speech are recorded from here. */
export const VoiceOnEvent = base('voice_on').describe('the microphone was turned on mid-Session');
export const PauseVia = z.enum(['button', 'voice']);
export const SessionPauseEvent = base('session_pause').extend({ via: PauseVia.default('button') });
export const SessionResumeEvent = base('session_resume').extend({
  gap_ms: z.number().int().nonnegative(),
  via: PauseVia.default('button'),
});

/** Mute (E10): the toolbar's mic button or Alt+Shift+M. Survives a pause; a Session that ends muted has no unmute. */
export const MuteVia = z.enum(['button', 'shortcut']);
export const MicMutedEvent = base('mic_muted')
  .extend({ via: MuteVia })
  .describe('the microphone went off: the audio holds silence from here, nothing is transcribed');
export const MicUnmutedEvent = base('mic_unmuted').extend({ via: MuteVia }).describe('the microphone came back on');

export const StrokePointSchema = PointSchema.extend({ t: Offset });
export const StrokeEvent = base('stroke').extend({
  stroke_id: z.string().min(1),
  t_end: Offset,
  points: z.array(StrokePointSchema).min(1).describe('page coordinates'),
  bbox: RectSchema,
  ...PageContextSchema.shape,
  shape: ShapeClass.nullable().describe('shape class; null until shape recognition (Slice 3)'),
  color: z
    .string()
    .regex(/^#[0-9a-f]{6}$/)
    .optional()
    .describe(
      'the ink colour, picked at pointer-down to stand out 3:1 against the page (packages/core/src/contrast.ts); absent: the default red',
    ),
});

/** One end of a Connector, resolved like an Annotation: the mark at that end, or a small box around the point. */
export const ConnectorEndSchema = z.object({
  point: PointSchema.describe('page coordinates of the arrow end'),
  bbox: RectSchema.describe('the region resolved: the mark at this end, or a small box around the point'),
  resolution: z.enum(['element', 'region']),
  candidates: z.array(CandidateSchema),
  pick: z.number().int().nonnegative().nullable(),
});
export const ConnectorSchema = z
  .object({
    stroke_ids: z.array(z.string()).min(1).describe('the arrow Strokes (one, or a shaft and a V)'),
    tail: ConnectorEndSchema.describe('the subject: where the arrow starts'),
    head: ConnectorEndSchema.describe('the destination: where the arrow points'),
  })
  .describe('an arrow in this Annotation joining two places (PRD P0-3)');

/** The Annotation's screenshot cut down to its picked element plus a margin (./crop.ts). */
export const AnnotationCropSchema = z
  .object({
    blob_id: z.string().min(1).describe('<screenshot_id>.crop, a blob of kind screenshot_crop'),
    path: z.string().describe('path inside an export folder: screenshots/<screenshot_id>.crop.png'),
    rect: RectSchema.describe("the crop in the screenshot's pixels"),
  })
  .describe(
    "the screenshot cropped to the picked element's box plus 16 CSS px; absent when nothing was picked or it was off screen",
  );

/** Who made an Annotation: the reviewer drawing, or a script on the page calling `window.__inkup` (E5). */
export const AnnotationSource = z.enum(['reviewer', 'page_api']);
export type AnnotationSource = z.infer<typeof AnnotationSource>;

/**
 * What a page_api call said about its element. A style or text change it asks for is a `style_edit` event on the
 * Annotation.
 */
export const PageApiNoteSchema = z.object({
  comment: z.string().max(2000).describe('what the calling script says should change'),
});
export type PageApiNote = z.infer<typeof PageApiNoteSchema>;

export const AnnotationEvent = base('annotation').extend({
  annotation_id: z.string().min(1),
  index: z.number().int().positive().describe('1-based order within the Session'),
  t_end: Offset,
  stroke_ids: z
    .array(z.string())
    .describe('empty only for an Object Select pick (close_reason object_select) or a page_api Annotation'),
  close_reason: CloseReason,
  bbox: RectSchema,
  ...PageContextSchema.shape,
  resolution: z.enum(['element', 'region']).describe('"region": nothing resolved, only bbox is meaningful'),
  candidates: z.array(CandidateSchema),
  pick: z.number().int().nonnegative().nullable().describe('index into candidates of the geometric pick'),
  screenshot_id: z.string().nullable(),
  connector: ConnectorSchema.nullable().default(null),
  comment: z
    .string()
    .max(2000)
    .nullable()
    .default(null)
    .describe(
      'what the reviewer typed or dictated in the comment box of an Object Select pick, or of a drawn Annotation in a Session without voice (E11); null when there was none',
    ),
  crop: AnnotationCropSchema.optional(),
  source: AnnotationSource.optional().describe("absent: 'reviewer'"),
  page_api: PageApiNoteSchema.optional().describe("the call's comment and changes, for source 'page_api'"),
});

/** An Annotation made by Object Select (it has no Strokes), not a drawn one that a pick closed. */
export const isObjectSelectPick = (a: { close_reason: CloseReason; stroke_ids: readonly string[] }) =>
  a.close_reason === 'object_select' && a.stroke_ids.length === 0;

export const ClickEvent = base('click').extend({
  ...PageContextSchema.shape,
  point: PointSchema,
  selector: z.string(),
  tag: z.string(),
  name: z.string().max(200),
});
export const NavigationEvent = base('navigation').extend({ url: z.string(), title: z.string(), overlay: overlayField });
export const TabSwitchEvent = base('tab_switch').extend({
  to_tab_id: z.number().int(),
  to_title: z.string(),
  away: z.boolean().describe('true when leaving the Session tab, false when returning'),
});
export const ScrollSettleEvent = base('scroll_settle').extend({ ...PageContextSchema.shape });

/** Clear all (E9): the reviewer emptied the page's overlay; what was on it then. */
export const OverlayClearedEvent = base('overlay_cleared').extend({
  url: z.string(),
  strokes: z.number().int().nonnegative().describe('Strokes removed from the page'),
  picks: z.number().int().nonnegative().describe('Object Select picks dropped before they were done'),
  comments: z.number().int().nonnegative().describe('open comment boxes closed unsaved'),
});

/**
 * The page's viewport was resized for the review (plan E6), or given back to the tab. 'frame_host': the page reloaded
 * into a sized frame of our own page; 'none': the tab's own size again. `scale` < 1 when the size is larger than the tab and is shown scaled down.
 */
export const ViewportMechanism = z.enum(['frame_host', 'none']);
export type ViewportMechanism = z.infer<typeof ViewportMechanism>;
export const ViewportChangeEvent = base('viewport_change').extend({
  width: z.number().int().positive().describe('viewport width now, CSS px'),
  height: z.number().int().positive().describe('viewport height now, CSS px'),
  scale: z.number().positive().max(1).describe('how much the page is scaled down to fit the tab (1: not at all)'),
  mechanism: ViewportMechanism,
});

export const ScreenshotTrigger = z.enum([
  'annotation',
  'click',
  'navigation',
  'voice_command',
  'panel',
  'shortcut',
  'text_comment',
  'page_api',
]);
export const ScreenshotEvent = base('screenshot').extend({
  screenshot_id: z.string().min(1).describe('also the key of the image in the blobs table'),
  path: z.string().describe('path inside an export folder, e.g. screenshots/<screenshot_id>.png'),
  mime: z.string(),
  trigger: ScreenshotTrigger,
  annotation_id: z.string().nullable(),
  ...PageContextSchema.shape,
});

/** The comment box speech was dictated into (E11): an Annotation's (Object Select, a drawn note) or a Text Comment's. */
export const DictationTarget = z.union([
  z.object({ annotation_id: z.string().min(1) }).strict(),
  z.object({ comment_id: z.string().min(1) }).strict(),
]);
export type DictationTarget = z.infer<typeof DictationTarget>;
export const WordSchema = z.object({ text: z.string(), t: Offset, t_end: Offset });
export const TranscriptSegmentEvent = base('transcript_segment').extend({
  segment_id: z.string().min(1),
  t_end: Offset,
  text: z.string(),
  ...TranscriptionInfoSchema.shape,
  words: z.array(WordSchema).nullable().describe('word timings; null for approximate engines'),
  confidence: z.number().min(0).max(1).nullable(),
  run_id: z
    .string()
    .min(1)
    .nullable()
    .default(null)
    .describe('the transcription run; null for the live run recorded during the Session'),
  target: DictationTarget.nullable()
    .default(null)
    .describe(
      "set when the speech was dictated into a comment box: it is that comment's text, not part of the Session transcript",
    ),
});
/**
 * A re-transcription of the stored audio from the review page (PRD P0-12). Appended after the Session, like the
 * review edits, with its segments (which carry `run_id`). Writing it makes it the active run.
 */
export const TranscriptionRunEvent = base('transcription_run').extend({
  run_id: z.string().min(1),
  ...TranscriptionInfoSchema.shape,
  model: z.string().describe('the engine model, e.g. nova-3, scribe_v2, onnx-community/whisper-base_timestamped'),
  segment_count: z.number().int().nonnegative(),
  created_at: z.iso.datetime(),
});
/** The reviewer picked which run the review page, Process and the export read. The latest pick wins. */
export const TranscriptSelectEvent = base('transcript_select').extend({
  run_id: z.string().min(1).nullable().describe('null: the live run'),
  edited_at: z.iso.datetime(),
});
export const TranscriptionFallbackEvent = base('transcription_fallback').extend({
  from: z.string(),
  to: z.string(),
  reason: z.string(),
});
export const VoiceCommandName = z.enum(['scratch_that', 'next', 'pin_that', 'snap', 'pause', 'resume']);
export const CommandTargetSchema = z.object({ kind: z.enum(['annotation', 'draft_item']), id: z.string().min(1) });
export const VoiceCommandEvent = base('voice_command').extend({
  t_end: Offset,
  command: VoiceCommandName,
  phrase: z.string().describe('the words as transcribed; removed from that segment before Process'),
  segment_id: z
    .string()
    .nullable()
    .describe('the transcript segment the phrase came from; null when it was heard while paused'),
  target: CommandTargetSchema.nullable().default(null).describe('what scratch that / pin that acted on'),
});
/** W3C Web Annotation TextQuoteSelector: the selected text and up to 32 characters either side, whitespace collapsed. */
export const TextQuoteAnchorSchema = z.object({
  exact: z.string().min(1).describe('the selected text'),
  prefix: z.string().describe('the text just before it'),
  suffix: z.string().describe('the text just after it'),
});
export type TextQuoteAnchor = z.infer<typeof TextQuoteAnchorSchema>;
/** The smallest element holding the whole selection, described like a Candidate. */
export const TextCommentElementSchema = CandidateSchema.pick({
  selector: true,
  tag: true,
  role: true,
  name: true,
  text: true,
  testid: true,
  id: true,
  classes: true,
  bbox: true,
});
/**
 * A Text Comment (E3): the reviewer selected text on the page and typed a comment on it. `t` is when the selection
 * was made, `t_end` when the comment was saved; speech in between belongs to it.
 */
export const TextCommentEvent = base('text_comment').extend({
  comment_id: z.string().min(1),
  index: z.number().int().positive().describe('1-based order within the Session (tN)'),
  t_end: Offset,
  selected_text: z.string().min(1).max(2000).describe('the selection as the page shows it, whitespace collapsed'),
  anchor: TextQuoteAnchorSchema,
  element: TextCommentElementSchema,
  comment: z.string().min(1).max(2000),
  bbox: RectSchema.describe('the selection'),
  ...PageContextSchema.shape,
  screenshot_id: z.string().nullable().describe('taken with the selection on screen and the comment box hidden'),
});
export const SpeechActivityEvent = base('speech_activity')
  .extend({ t_end: Offset })
  .describe('a span of speech detected by the VAD');
export const Category = z.enum(['layout', 'style', 'copy', 'content', 'behavior', 'bug', 'question']);
export const LocationRole = z.enum(['subject', 'reference', 'destination']);
export type LocationRole = z.infer<typeof LocationRole>;

/** A Draft Item's Location, as the panel card shows it: role, element name, and the Annotation it came from. */
export const DraftLocationSchema = z.object({
  role: LocationRole,
  element: z.string().describe("short element name, e.g. button 'Get started'"),
  selector: z.string().nullable().describe('the Candidate selector the draft chose; null for a region or the page'),
  annotation: z
    .number()
    .int()
    .positive()
    .nullable()
    .describe('Annotation number (#n); null for speech with no Annotation'),
});
export type DraftLocation = z.infer<typeof DraftLocationSchema>;

/**
 * A Draft Item (PRD P0-10): a provisional Change Item from a live pass. Written after the Annotations it covers,
 * so `t` is later than their `t_end` (scratch that compares the two to find the newest).
 */
export const DraftItemEvent = base('draft_item').extend({
  draft_id: z.string().min(1).describe('d1, d2, … in the order written'),
  pass_id: z.string().min(1).describe('the live pass that produced it'),
  model: z.string().describe('the Draft model ID'),
  title: z.string(),
  category: Category,
  intent: z.string().describe('one sentence: what the reviewer wants'),
  transcript: z.string().describe('the reviewer words it came from, verbatim'),
  locations: z.array(DraftLocationSchema),
  annotation_ids: z.array(z.string()).describe('the Annotations it covers'),
});
/** Discard or pin, by a click on the panel card or by voice (scratch that, pin that). The latest action wins. */
export const DraftActionEvent = base('draft_action').extend({
  draft_id: z.string().min(1),
  action: z.enum(['discard', 'pin']),
  source: z.enum(['click', 'voice']),
});

// Review-page edits (PRD P0-11 editable transcript, P0-12 item editing). The log stays append-only: an edit is a
// new event stamped at the Session's end (`t` = duration), in the order it was made. Readers fold them in
// (packages/core/src/review-edits.ts); the raw segments and the generated Change Items are never rewritten.
export const TranscriptEditEvent = base('transcript_edit').extend({
  segment_id: z.string().min(1).describe('the transcript_segment this replaces the text of; the latest edit wins'),
  text: z.string(),
  edited_at: z.iso.datetime(),
});
const itemId = z.string().min(1);
export const ItemEditOp = z.discriminatedUnion('op', [
  z.object({
    op: z.literal('edit'),
    item_id: itemId,
    changes: z.object({
      title: z.string().min(1).optional(),
      intent: z.string().min(1).optional(),
      category: Category.optional(),
      agent_prompt: z.string().min(1).optional(),
      ambiguity: z.string().nullable().optional().describe('null: the item has no ambiguity any more'),
    }),
    origin: z
      .literal('combine')
      .optional()
      .describe(
        "combine: written by the merge model right after a merge (the review page's Combine), not typed by the reviewer",
      ),
  }),
  z.object({ op: z.literal('delete'), item_id: itemId }),
  z
    .object({ op: z.literal('merge'), into: itemId, from: itemId })
    .describe('`from` is folded into `into`, which keeps its id, title and category'),
  z
    .object({ op: z.literal('split'), item_id: itemId, new_id: itemId })
    .describe('a copy of the item under `new_id`, placed after it, to be edited'),
  z.object({ op: z.literal('reorder'), order: z.array(itemId) }).describe('the full item order after a drag'),
  z
    .object({ op: z.literal('undo') })
    .describe('takes back the latest step not yet undone (a merge and its combine are one step)'),
  z
    .object({ op: z.literal('redo') })
    .describe('puts back the latest undone step; a new edit clears what can be redone'),
]);
export type ItemEditOp = z.infer<typeof ItemEditOp>;
export const ItemEditEvent = base('item_edit').extend({
  run_id: z.string().min(1).describe('the Process run whose Change Items this edits'),
  edited_at: z.iso.datetime(),
  edit: ItemEditOp,
});

/** One value to change on an element: its computed value now, and what it should become. */
export const ValueChangeSchema = z.object({
  from: z.string().describe("the element's computed value when the change was recorded"),
  to: z.string().describe('the value it should become, e.g. 20px 32px or var(--brand)'),
});
export type ValueChange = z.infer<typeof ValueChangeSchema>;
/**
 * Exact style or text changes to an element an Annotation names (from the page API, E5). Each carries the whole
 * difference, so the latest `style_edit` of an Annotation wins. The page itself is never modified.
 */
export const StyleEditEvent = base('style_edit').extend({
  annotation_id: z
    .string()
    .min(1)
    .describe('the Annotation whose element the changes are for (a page_api Annotation whose script asked for them)'),
  selector: z.string().describe("the element's selector"),
  changes: z
    .record(z.string(), ValueChangeSchema)
    .describe('CSS property (kebab-case) → from/to; empty when only the text changed'),
  text: ValueChangeSchema.optional().describe("the element's text, when it should say something else"),
});

export const SessionEndEvent = base('session_end').extend({
  reason: z.enum(['stop', 'panel_closed', 'tab_closed', 'shortcut']),
  duration_ms: z.number().int().nonnegative(),
});

export const TimelineEventSchema = z.discriminatedUnion('type', [
  SessionStartEvent,
  SessionPauseEvent,
  SessionResumeEvent,
  StrokeEvent,
  AnnotationEvent,
  ClickEvent,
  NavigationEvent,
  TabSwitchEvent,
  ScrollSettleEvent,
  ScreenshotEvent,
  TranscriptSegmentEvent,
  TranscriptionFallbackEvent,
  VoiceCommandEvent,
  SpeechActivityEvent,
  DraftItemEvent,
  DraftActionEvent,
  SessionEndEvent,
  TranscriptEditEvent,
  ItemEditEvent,
  TranscriptionRunEvent,
  TranscriptSelectEvent,
  ViewportChangeEvent,
  StyleEditEvent,
  TextCommentEvent,
  MicMutedEvent,
  MicUnmutedEvent,
  VoiceOnEvent,
  OverlayClearedEvent,
]);

export type TimelineEvent = z.infer<typeof TimelineEventSchema>;
export type EventType = TimelineEvent['type'];
export type EventOf<T extends EventType> = Extract<TimelineEvent, { type: T }>;
/** An event before the log assigns its id. */
export type NewEvent = TimelineEvent extends infer E ? (E extends TimelineEvent ? Omit<E, 'id'> : never) : never;

export const EVENT_TYPES = TimelineEventSchema.options.map((o) => o.shape.type.value) as EventType[];

/** Stable order: by t, then by the order events were appended (seq). */
export function sortTimeline<E extends { t: number }>(events: readonly (E & { seq?: number })[]): E[] {
  return [...events].sort((a, b) => a.t - b.t || (a.seq ?? 0) - (b.seq ?? 0));
}
