// contract/protocol.schema.json is generated by `pnpm schema`; this fails when it is stale.
import { readFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';
import { renderSchema, SCHEMA_FILE } from '../scripts/gen-schema.ts';

describe('contract/protocol.schema.json', () => {
  it('matches the Zod schemas (run `pnpm schema` to regenerate)', () => {
    expect(readFileSync(SCHEMA_FILE, 'utf8')).toBe(renderSchema());
  });
  it('defines every message', () => {
    const text = renderSchema();
    for (const t of ['hello', 'paired', 'welcome', 'event', 'ack', 'error'])
      expect(text).toMatch(new RegExp(`"enum": \\[\\s*"${t}"\\s*\\]`));
  });
});
