// `pnpm fixtures:react`: bundles the development builds of react and react-dom/client (the versions the extension
// uses) into fixtures/site/vendor/react-dev.js, one script that sets window.React and window.ReactDOM. The React
// fixture page (fixtures/site/react.html) loads it, so the source-mapping e2e needs no network. Commit the output.

import { mkdirSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const web = join(root, 'extensions', 'web');
// rolldown is not a root dependency: reach it through WXT, which bundles with it.
const fromWxt = createRequire(createRequire(join(web, 'package.json')).resolve('wxt'));
type Rolldown = (
  options: Record<string, unknown>,
) => Promise<{ generate(o: Record<string, unknown>): Promise<{ output: { code: string }[] }> }>;
const { rolldown } = (await import(fromWxt.resolve('rolldown'))) as { rolldown: Rolldown };

const entry = `import * as React from 'react'; import * as ReactDOM from 'react-dom/client'; window.React = React; window.ReactDOM = ReactDOM;`;
const bundle = await rolldown({
  input: 'virtual:react-dev',
  cwd: web,
  platform: 'browser',
  transform: { define: { 'process.env.NODE_ENV': '"development"' } },
  plugins: [
    {
      name: 'entry',
      resolveId: (id: string) => (id === 'virtual:react-dev' ? id : null),
      load: (id: string) => (id === 'virtual:react-dev' ? entry : null),
    },
  ],
});
const { output } = await bundle.generate({ format: 'iife', minify: true });
const code = output[0]!.code;
const out = join(root, 'fixtures', 'site', 'vendor', 'react-dev.js');
mkdirSync(dirname(out), { recursive: true });
const version = createRequire(join(web, 'package.json'))('react/package.json').version as string;
writeFileSync(
  out,
  `/* React ${version} and react-dom/client, development builds (MIT). Generated by scripts/vendor-react-fixture.ts. */\n${code}`,
);
console.log(`wrote ${out} (${(code.length / 1024).toFixed(0)} KiB)`);
