// scripts/install-hooks.mjs under parallel `pnpm install` in worktrees that share one .git: one install, no
// `.legacy` self-copies, and a self-copy left by an earlier race heals.
import { spawn } from 'node:child_process';
import { chmodSync, existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { afterEach, beforeEach, describe, expect, it } from 'vitest';

const SCRIPT = resolve(import.meta.dirname, '../../scripts/install-hooks.mjs');
const TYPES = ['pre-commit', 'pre-push', 'commit-msg'];
const HOOK = (type: string) =>
  `#!/usr/bin/env bash\n# File generated by pre-commit: https://pre-commit.com\n# ID: 138fd403232d2ddd5efb44317e38bf03\n# ${type}\n`;

// Like the real `pre-commit install`: a hook that is not pre-commit's is moved aside as `<hook>.legacy`, and the new
// hook is written in two steps, so a racing install sees the half-written file as foreign and moves it.
const STUB = `#!/usr/bin/env bash
set -e
[ "$1" = "--version" ] && { echo "pre-commit 4.6.0"; exit 0; }
[ "$1" = "install" ] || exit 2
hooks="$(git rev-parse --git-common-dir)/hooks"
mkdir -p "$hooks"
echo install >> "$STUB_LOG"
for t in ${TYPES.join(' ')}; do
  f="$hooks/$t"
  if [ -f "$f" ] && ! grep -q '^# ID: ' "$f"; then mv "$f" "$f.legacy"; fi
  exec 3>"$f"
  echo '#!/usr/bin/env bash' >&3
  sleep 0.05
  printf '# File generated by pre-commit: https://pre-commit.com\\n# ID: 138fd403232d2ddd5efb44317e38bf03\\n# %s\\n' "$t" >&3
  exec 3>&-
  chmod +x "$f"
done
`;

let dir: string;
let repo: string;
let hooks: string;
let log: string;
let env: NodeJS.ProcessEnv;

function run(cwd = repo) {
  return new Promise<{ code: number | null; out: string }>((done) => {
    const child = spawn(process.execPath, [SCRIPT], { cwd, env });
    let out = '';
    child.stdout.on('data', (d) => {
      out += d;
    });
    child.stderr.on('data', (d) => {
      out += d;
    });
    child.on('close', (code) => done({ code, out }));
  });
}

const installs = () => (existsSync(log) ? readFileSync(log, 'utf8').trim().split('\n').length : 0);
const legacies = () => TYPES.filter((t) => existsSync(join(hooks, `${t}.legacy`)));

function git(...args: string[]) {
  return new Promise<void>((done, fail) =>
    spawn('git', args, { cwd: repo, env }).on('close', (c) => (c === 0 ? done() : fail(new Error(`git ${args}`)))),
  );
}

describe('install-hooks', () => {
  beforeEach(async () => {
    dir = mkdtempSync(join(tmpdir(), 'inkup-hooks-'));
    repo = join(dir, 'repo');
    const bin = join(dir, 'bin');
    mkdirSync(repo);
    mkdirSync(bin);
    log = join(dir, 'installs.log');
    writeFileSync(join(bin, 'pre-commit'), STUB);
    chmodSync(join(bin, 'pre-commit'), 0o755);
    env = { ...process.env, CI: '', PATH: `${bin}:${process.env.PATH}`, STUB_LOG: log };
    await git('init', '-q');
    // git init ships only *.sample hooks; start from none so every hook is foreign-free.
    rmSync(join(repo, '.git', 'hooks'), { recursive: true, force: true });
    hooks = join(repo, '.git', 'hooks');
    writeFileSync(join(repo, '.pre-commit-config.yaml'), `default_install_hook_types: [${TYPES.join(', ')}]\n`);
  });

  afterEach(() => rmSync(dir, { recursive: true, force: true }));

  it('installs once when six installs run at the same time, and leaves no .legacy', async () => {
    const results = await Promise.all(Array.from({ length: 6 }, () => run()));
    expect(results.map((r) => r.code)).toEqual([0, 0, 0, 0, 0, 0]);
    expect(installs()).toBe(1);
    expect(legacies()).toEqual([]);
    for (const t of TYPES) expect(readFileSync(join(hooks, t), 'utf8')).toBe(HOOK(t));
    expect(existsSync(join(repo, '.git', 'inkup-install-hooks.lock'))).toBe(false);

    // Idempotent: a later batch finds the hooks in place and installs nothing.
    await Promise.all(Array.from({ length: 6 }, () => run()));
    expect(installs()).toBe(1);
  });

  it('shares the lock and the hooks across worktrees', async () => {
    await git(
      '-c',
      'user.name=t',
      '-c',
      'user.email=t@t',
      'commit',
      '-q',
      '--allow-empty',
      '-m',
      'init',
      '--no-verify',
    );
    const trees = ['a', 'b', 'c'].map((n) => join(dir, n));
    for (const [i, t] of trees.entries()) await git('worktree', 'add', '-q', '-b', `w${i}`, t);
    for (const t of trees)
      writeFileSync(join(t, '.pre-commit-config.yaml'), readFileSync(join(repo, '.pre-commit-config.yaml')));
    const results = await Promise.all([...trees, ...trees].map((t) => run(t)));
    expect(results.every((r) => r.code === 0)).toBe(true);
    expect(installs()).toBe(1);
    expect(legacies()).toEqual([]);
  });

  it('heals a .legacy that is a copy of the pre-commit hook itself, without reinstalling', async () => {
    mkdirSync(hooks);
    for (const t of TYPES) writeFileSync(join(hooks, t), HOOK(t));
    writeFileSync(join(hooks, 'pre-commit.legacy'), HOOK('pre-commit'));
    writeFileSync(join(hooks, 'pre-push.legacy'), HOOK('pre-push'));

    const { code, out } = await run();
    expect(code).toBe(0);
    expect(legacies()).toEqual([]);
    expect(installs()).toBe(0);
    expect(out).toContain('removed pre-commit.legacy');
  });

  it('keeps a .legacy that is a hook of your own', async () => {
    mkdirSync(hooks);
    for (const t of TYPES) writeFileSync(join(hooks, t), HOOK(t));
    writeFileSync(join(hooks, 'pre-commit.legacy'), '#!/bin/sh\necho mine\n');

    expect((await run()).code).toBe(0);
    expect(legacies()).toEqual(['pre-commit']);
  });

  it('stays quiet in CI and outside a git checkout', async () => {
    env.CI = 'true';
    const ci = await run();
    expect(ci).toEqual({ code: 0, out: '[hooks] CI detected; not installing git hooks.\n' });

    env.CI = '';
    const outside = join(dir, 'tarball');
    mkdirSync(outside);
    expect(await run(outside)).toEqual({ code: 0, out: '' });
    expect(installs()).toBe(0);
  });
});
