// scripts/install-hooks.mjs under parallel `pnpm install` in worktrees that share one .git: one install, no
// `.legacy` self-copies, and a self-copy left by an earlier race heals.
import { spawn, spawnSync } from 'node:child_process';
import {
  chmodSync,
  existsSync,
  mkdirSync,
  mkdtempSync,
  readdirSync,
  readFileSync,
  realpathSync,
  rmSync,
  writeFileSync,
} from 'node:fs';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { afterEach, beforeEach, describe, expect, it } from 'vitest';

const SCRIPT = resolve(import.meta.dirname, '../../scripts/install-hooks.mjs');
const TYPES = ['pre-commit', 'pre-push', 'commit-msg'];
const HOOK = (type: string) =>
  `#!/usr/bin/env bash\n# File generated by pre-commit: https://pre-commit.com\n# ID: 138fd403232d2ddd5efb44317e38bf03\n# ${type}\n`;

// Like the real `pre-commit install`: a hook that is not pre-commit's is moved aside as `<hook>.legacy`, and the new
// hook is written in two steps, so a racing install sees the half-written file as foreign and moves it.
const STUB = `#!/usr/bin/env bash
set -e
[ "$1" = "--version" ] && { echo "pre-commit 4.6.0"; exit 0; }
[ "$1" = "install" ] || exit 2
hooks="$(git rev-parse --git-common-dir)/hooks"
mkdir -p "$hooks"
echo install >> "$STUB_LOG"
for t in ${TYPES.join(' ')}; do
  f="$hooks/$t"
  if [ -f "$f" ] && ! grep -q '^# ID: ' "$f"; then mv "$f" "$f.legacy"; fi
  exec 3>"$f"
  echo '#!/usr/bin/env bash' >&3
  sleep 0.05
  printf '# File generated by pre-commit: https://pre-commit.com\\n# ID: 138fd403232d2ddd5efb44317e38bf03\\n# %s\\n' "$t" >&3
  exec 3>&-
  chmod +x "$f"
done
`;

let dir: string;
let repo: string;
let hooks: string;
let log: string;
let env: NodeJS.ProcessEnv;

/**
 * The child environment, built without the caller's GIT_* variables. `pnpm test` runs from the pre-push hook, where
 * GIT_DIR, GIT_INDEX_FILE and the rest point at the real repo; passed on, they made `git init` here reinitialise it.
 * No system config, HOME in the temp dir, and git never searches above the temp dir either.
 */
function isolatedEnv(bin: string): NodeJS.ProcessEnv {
  const outer = Object.fromEntries(Object.entries(process.env).filter(([k]) => !k.startsWith('GIT_')));
  return {
    ...outer,
    CI: '',
    PATH: `${bin}:${process.env.PATH}`,
    STUB_LOG: log,
    HOME: dir,
    GIT_CONFIG_NOSYSTEM: '1',
    GIT_CEILING_DIRECTORIES: dir,
  };
}

/** Runs git in `cwd`, after checking that the repo it would write to is inside the temp dir. */
function git(cwd: string, ...args: string[]) {
  const found = spawnSync('git', ['rev-parse', '--absolute-git-dir'], { cwd, env, encoding: 'utf8' });
  const gitDir = found.status === 0 ? found.stdout.trim() : null;
  const root = realpathSync(dir);
  if (gitDir ? !gitDir.startsWith(`${root}/`) : args[0] !== 'init')
    throw new Error(`refusing \`git ${args.join(' ')}\` in ${cwd}: its git dir ${gitDir} is outside ${root}`);
  const done = spawnSync('git', args, { cwd, env, encoding: 'utf8' });
  if (done.status !== 0) throw new Error(`git ${args.join(' ')}: ${done.stderr}`);
}

function run(cwd = repo) {
  return new Promise<{ code: number | null; out: string }>((done) => {
    const child = spawn(process.execPath, [SCRIPT], { cwd, env });
    let out = '';
    child.stdout.on('data', (d) => {
      out += d;
    });
    child.stderr.on('data', (d) => {
      out += d;
    });
    child.on('close', (code) => done({ code, out }));
  });
}

const installs = () => (existsSync(log) ? readFileSync(log, 'utf8').trim().split('\n').length : 0);
const legacies = () => TYPES.filter((t) => existsSync(join(hooks, `${t}.legacy`)));

/** A temp dir with a stub pre-commit on PATH and an empty repo with no hooks. */
function setup() {
  dir = mkdtempSync(join(tmpdir(), 'inkup-hooks-'));
  repo = join(dir, 'repo');
  const bin = join(dir, 'bin');
  mkdirSync(repo);
  mkdirSync(bin);
  log = join(dir, 'installs.log');
  writeFileSync(join(bin, 'pre-commit'), STUB);
  chmodSync(join(bin, 'pre-commit'), 0o755);
  env = isolatedEnv(bin);
  git(repo, 'init', '-q');
  if (!existsSync(join(repo, '.git', 'HEAD'))) throw new Error(`git init did not create ${repo}/.git`);
  // git init ships only *.sample hooks; start from none.
  rmSync(join(repo, '.git', 'hooks'), { recursive: true, force: true });
  hooks = join(repo, '.git', 'hooks');
  writeFileSync(join(repo, '.pre-commit-config.yaml'), `default_install_hook_types: [${TYPES.join(', ')}]\n`);
}

function commit(cwd: string) {
  git(cwd, '-c', 'user.name=t', '-c', 'user.email=t@t', 'commit', '-q', '--allow-empty', '-m', 'init', '--no-verify');
}

/** Every file under `root`, with its contents: a before/after fingerprint of a repo. */
function snapshot(root: string): Record<string, string> {
  const files: Record<string, string> = {};
  for (const entry of readdirSync(root, { recursive: true, withFileTypes: true }))
    if (entry.isFile()) {
      const path = join(entry.parentPath, entry.name);
      files[path.slice(root.length)] = readFileSync(path, 'base64');
    }
  return files;
}

describe('install-hooks', () => {
  beforeEach(setup);

  afterEach(() => rmSync(dir, { recursive: true, force: true }));

  it('installs once when six installs run at the same time, and leaves no .legacy', async () => {
    const results = await Promise.all(Array.from({ length: 6 }, () => run()));
    expect(results.map((r) => r.code)).toEqual([0, 0, 0, 0, 0, 0]);
    expect(installs()).toBe(1);
    expect(legacies()).toEqual([]);
    for (const t of TYPES) expect(readFileSync(join(hooks, t), 'utf8')).toBe(HOOK(t));
    expect(existsSync(join(repo, '.git', 'inkup-install-hooks.lock'))).toBe(false);

    // Idempotent: a later batch finds the hooks in place and installs nothing.
    await Promise.all(Array.from({ length: 6 }, () => run()));
    expect(installs()).toBe(1);
  });

  it('shares the lock and the hooks across worktrees', async () => {
    commit(repo);
    const trees = ['a', 'b', 'c'].map((n) => join(dir, n));
    for (const [i, t] of trees.entries()) git(repo, 'worktree', 'add', '-q', '-b', `w${i}`, t);
    for (const t of trees)
      writeFileSync(join(t, '.pre-commit-config.yaml'), readFileSync(join(repo, '.pre-commit-config.yaml')));
    const results = await Promise.all([...trees, ...trees].map((t) => run(t)));
    expect(results.every((r) => r.code === 0)).toBe(true);
    expect(installs()).toBe(1);
    expect(legacies()).toEqual([]);
  });

  it('heals a .legacy that is a copy of the pre-commit hook itself, without reinstalling', async () => {
    mkdirSync(hooks);
    for (const t of TYPES) writeFileSync(join(hooks, t), HOOK(t));
    writeFileSync(join(hooks, 'pre-commit.legacy'), HOOK('pre-commit'));
    writeFileSync(join(hooks, 'pre-push.legacy'), HOOK('pre-push'));

    const { code, out } = await run();
    expect(code).toBe(0);
    expect(legacies()).toEqual([]);
    expect(installs()).toBe(0);
    expect(out).toContain('removed pre-commit.legacy');
  });

  it('keeps a .legacy that is a hook of your own', async () => {
    mkdirSync(hooks);
    for (const t of TYPES) writeFileSync(join(hooks, t), HOOK(t));
    writeFileSync(join(hooks, 'pre-commit.legacy'), '#!/bin/sh\necho mine\n');

    expect((await run()).code).toBe(0);
    expect(legacies()).toEqual(['pre-commit']);
  });

  it('stays quiet in CI and outside a git checkout', async () => {
    env.CI = 'true';
    const ci = await run();
    expect(ci).toEqual({ code: 0, out: '[hooks] CI detected; not installing git hooks.\n' });

    env.CI = '';
    const outside = join(dir, 'tarball');
    mkdirSync(outside);
    expect(await run(outside)).toEqual({ code: 0, out: '' });
    expect(installs()).toBe(0);
  });

  it('leaves the repo that GIT_DIR points at alone, as inside a git hook', async () => {
    const decoyDir = mkdtempSync(join(tmpdir(), 'inkup-decoy-'));
    const decoy = join(decoyDir, 'repo');
    try {
      // The decoy, made with this suite's own guarded helpers.
      const [outerDir, outerRepo, outerEnv] = [dir, repo, env];
      [dir, repo] = [decoyDir, decoy];
      mkdirSync(decoy);
      git(decoy, 'init', '-q');
      commit(decoy);
      [dir, repo, env] = [outerDir, outerRepo, outerEnv];
      const before = snapshot(join(decoy, '.git'));

      // What a pre-push hook exports, pointing at the decoy.
      const hookEnv = {
        GIT_DIR: join(decoy, '.git'),
        GIT_WORK_TREE: decoy,
        GIT_INDEX_FILE: join(decoy, '.git', 'index'),
        GIT_COMMON_DIR: join(decoy, '.git'),
        GIT_OBJECT_DIRECTORY: join(decoy, '.git', 'objects'),
      };
      Object.assign(process.env, hookEnv);
      try {
        rmSync(dir, { recursive: true, force: true });
        setup();
        commit(repo);
        git(repo, 'worktree', 'add', '-q', '-b', 'w0', join(dir, 'a'));
        // The script itself, run with the hook's variables, installs into the repo it runs in.
        const direct = spawnSync(process.execPath, [SCRIPT], { cwd: repo, env: { ...env, ...hookEnv } });
        expect(direct.status).toBe(0);
      } finally {
        for (const k of Object.keys(hookEnv)) delete process.env[k];
      }

      expect(installs()).toBe(1);
      for (const t of TYPES) expect(readFileSync(join(hooks, t), 'utf8')).toBe(HOOK(t));
      expect(snapshot(join(decoy, '.git'))).toEqual(before);
    } finally {
      rmSync(decoyDir, { recursive: true, force: true });
    }
  });
});
