// contract/session.schema.json is generated by `pnpm schema`; this fails when it is stale.
import { readFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';
import { renderSchema, SCHEMA_FILE } from '../../scripts/gen-schema.ts';

describe('contract/session.schema.json', () => {
  it('matches the Zod schema (run `pnpm schema` to regenerate)', () => {
    expect(readFileSync(SCHEMA_FILE, 'utf8')).toBe(renderSchema());
  });
  it('documents every event type', () => {
    const text = renderSchema();
    for (const t of ['session_start', 'stroke', 'annotation', 'screenshot', 'transcript_segment', 'session_end'])
      expect(text).toContain(`"const": "${t}"`);
  });
});
